name: komitan_kutter
description: Video Cutter Offline
publish_to: 'none'
version: 1.0.0+1

environment:
  # [FIX] Dart 3.0.0 (Flutter 3.10+) sampai sebelum 4.0.0
  # Kemarin salah tulis 3.10.0 (Itu versi Flutter, bukan Dart)
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Paket FFmpeg Pilihan Anda
  ffmpeg_kit_flutter_new_min: ^3.1.0
  
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  intl: ^0.18.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
