name: komitan_kutter
description: Video Cutter Offline
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # [GANTI KE VERSI STABIL]
  # Versi 4.5.1 berjalan mulus di SDK 31-33. Tidak butuh SDK 35.
  ffmpeg_kit_flutter_full_gpl: ^4.5.1

  file_picker: ^5.2.5 # Downgrade dikit biar aman
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  intl: ^0.18.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
