name: komitan_kutter
description: Video Cutter Offline
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new_min: ^3.1.0
  file_picker: ^8.1.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  archive: ^4.0.7
  video_player: ^2.10.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
